Module 4. Created device-service, edited component diagram and constructed diagrams related to device service

diff --git a/infrastructure/docker-compose.yaml b/infrastructure/docker-compose.yaml
--- a/infrastructure/docker-compose.yaml
+++ b/infrastructure/docker-compose.yaml
@@ -257,28 +257,28 @@ services:
       timeout: 5s
       retries: 5
 
-  #  kafka-ui:
-  #    image: provectuslabs/kafka-ui:latest
-  #    container_name: kafka-ui
-  #    ports:
-  #      - "8070:8080"
-  #    environment:
-  #      - KAFKA_CLUSTERS_0_NAME=local
-  #      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
-  #      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
-  #      - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://schema-registry:8081
-  #    depends_on:
-  #      kafka:
-  #        condition: service_healthy
-  #      schema-registry:
-  #        condition: service_healthy
-  #    networks:
-  #      - iot-platform-net
-  #    healthcheck:
-  #      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080" ]
-  #      interval: 10s
-  #      timeout: 5s
-  #      retries: 5
+  kafka-ui:
+    image: provectuslabs/kafka-ui:latest
+    container_name: kafka-ui
+    ports:
+      - "8070:8080"
+    environment:
+      - KAFKA_CLUSTERS_0_NAME=local
+      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
+      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
+      - KAFKA_CLUSTERS_0_SCHEMAREGISTRY=http://schema-registry:8081
+    depends_on:
+      kafka:
+        condition: service_healthy
+      schema-registry:
+        condition: service_healthy
+    networks:
+      - iot-platform-net
+    healthcheck:
+      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080" ]
+      interval: 10s
+      timeout: 5s
+      retries: 5
 
 
   minio:
@@ -326,6 +326,7 @@ services:
       keycloak-postgres:
         condition: service_healthy
     environment:
+      JAVA_OPTS: -Dkeycloak.migration.usersExportStrategy=REALM_FILE
       KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
       KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
       KC_DB: postgres
@@ -333,21 +334,20 @@ services:
       KC_DB_URL_HOST: keycloak-postgres
       KC_DB_USERNAME: ${KEYCLOAK_POSTGRES_USERNAME}
       KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
-      KC_HOSTNAME: "localhost"
       KC_HTTP_MANAGEMENT_PORT: 9002
       KC_HOSTNAME_STRICT: "false"
       KC_PROXY: "edge"
-
       KC_METRICS_ENABLED: "true"
       KC_HEALTH_ENABLED: "true"
     volumes:
       - keycloak_data:/opt/keycloak/data
-    command: start-dev --metrics-enabled=true
+      - ./infrastructure/keycloak/realm-config.json:/opt/keycloak/data/import/realm-config.json
+    command: start-dev --import-realm --metrics-enabled=true
     ports:
       - "8080:8080"
       - "9002:9002"
     healthcheck:
-      test: [ "CMD-SHELL", "curl -fsS http://localhost:9000/health/ready || exit 1" ]
+      test: [ "CMD-SHELL", "curl -fsS http://localhost:9002/health/ready || exit 1" ]
       interval: 10s
       timeout: 5s
       retries: 30
@@ -549,56 +549,56 @@ services:
     networks:
       - iot-platform-net
 
-  event-collector-service:
-    build:
-      context: ../event-collector-service/
-      dockerfile: Dockerfile
-      args:
-        NEXUS_URL: ${NEXUS_URL}
-        NEXUS_USERNAME: ${NEXUS_USERNAME}
-        NEXUS_PASSWORD: ${NEXUS_PASSWORD}
-    container_name: event-collector-service
-    ports:
-      - "9099:9099"
-    environment:
-      CASSANDRA_HOST: ${CASSANDRA_HOST}
-      CASSANDRA_PORT: ${CASSANDRA_PORT}
-      CASSANDRA_USER: ${CASSANDRA_USER}
-      CASSANDRA_PASSWORD: ${CASSANDRA_PASSWORD}
-      CASSANDRA_DATABASE_URL: ${CASSANDRA_DATABASE_URL}
-      CASSANDRA_KEYSPACE: ${CASSANDRA_KEYSPACE}
-      CASSANDRA_DATACENTER: ${CASSANDRA_DATACENTER}
-      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
-      SCHEMA_REGISTRY_URL: ${SCHEMA_REGISTRY_URL}
-      CONSUMER_GROUP_ID: ${CONSUMER_GROUP_ID}
-      KAFKA_CONCURRENCY: ${KAFKA_CONCURRENCY}
-      KAFKA_POLL_TIMEOUT: ${KAFKA_POLL_TIMEOUT}
-      KAFKA_BATCH_LISTENER_ENABLED: ${KAFKA_BATCH_LISTENER_ENABLED}
-      ALLOY_URL: ${ALLOY_URL}
-      FLYWAY_MIGRATION_CLASSPATH: ${FLYWAY_MIGRATION_CLASSPATH}
-      FLYWAY_MIGRATION_SUFFIXES: ${FLYWAY_MIGRATION_SUFFIXES}
-      FLYWAY_MIGRATION_SCHEMA: ${FLYWAY_MIGRATION_SCHEMA}
-#    volumes:
-#      - /var/run/docker.sock:/var/run/docker.sock
-    networks:
-      - iot-platform-net
-    depends_on:
-      cassandra:
-        condition: service_healthy
-      kafka:
-        condition: service_healthy
-      schema-registry:
-        condition: service_healthy
-      nexus:
-        condition: service_healthy
-      avro-schemas:
-        condition: service_completed_successfully
-    healthcheck:
-      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:9099/actuator/health" ]
-      interval: 15s
-      timeout: 5s
-      retries: 5
-      start_period: 30s
+#  event-collector-service:
+#    build:
+#      context: ../event-collector-service/
+#      dockerfile: Dockerfile
+#      args:
+#        NEXUS_URL: ${NEXUS_URL}
+#        NEXUS_USERNAME: ${NEXUS_USERNAME}
+#        NEXUS_PASSWORD: ${NEXUS_PASSWORD}
+#    container_name: event-collector-service
+#    ports:
+#      - "9099:9099"
+#    environment:
+#      CASSANDRA_HOST: ${CASSANDRA_HOST}
+#      CASSANDRA_PORT: ${CASSANDRA_PORT}
+#      CASSANDRA_USER: ${CASSANDRA_USER}
+#      CASSANDRA_PASSWORD: ${CASSANDRA_PASSWORD}
+#      CASSANDRA_DATABASE_URL: ${CASSANDRA_DATABASE_URL}
+#      CASSANDRA_KEYSPACE: ${CASSANDRA_KEYSPACE}
+#      CASSANDRA_DATACENTER: ${CASSANDRA_DATACENTER}
+#      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
+#      SCHEMA_REGISTRY_URL: ${SCHEMA_REGISTRY_URL}
+#      CONSUMER_GROUP_ID: ${CONSUMER_GROUP_ID}
+#      KAFKA_CONCURRENCY: ${KAFKA_CONCURRENCY}
+#      KAFKA_POLL_TIMEOUT: ${KAFKA_POLL_TIMEOUT}
+#      KAFKA_BATCH_LISTENER_ENABLED: ${KAFKA_BATCH_LISTENER_ENABLED}
+#      ALLOY_URL: ${ALLOY_URL}
+#      FLYWAY_MIGRATION_CLASSPATH: ${FLYWAY_MIGRATION_CLASSPATH}
+#      FLYWAY_MIGRATION_SUFFIXES: ${FLYWAY_MIGRATION_SUFFIXES}
+#      FLYWAY_MIGRATION_SCHEMA: ${FLYWAY_MIGRATION_SCHEMA}
+##    volumes:
+##      - /var/run/docker.sock:/var/run/docker.sock
+#    networks:
+#      - iot-platform-net
+#    depends_on:
+#      cassandra:
+#        condition: service_healthy
+#      kafka:
+#        condition: service_healthy
+#      schema-registry:
+#        condition: service_healthy
+#      nexus:
+#        condition: service_healthy
+#      avro-schemas:
+#        condition: service_completed_successfully
+#    healthcheck:
+#      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:9099/actuator/health" ]
+#      interval: 15s
+#      timeout: 5s
+#      retries: 5
+#      start_period: 30s
 
   nexus:
     image: sonatype/nexus3:3.76.0
@@ -618,84 +618,84 @@ services:
     networks:
       - iot-platform-net
 
-  avro-schemas:
-    build:
-      context: ../avro-schemas/
-      dockerfile: Dockerfile
-    environment:
-      NEXUS_URL: ${NEXUS_AVRO_URL}
-      NEXUS_USERNAME: ${NEXUS_USERNAME}
-      NEXUS_PASSWORD: ${NEXUS_PASSWORD}
-    networks:
-      - iot-platform-net
-    depends_on:
-      nexus:
-        condition: service_healthy
-    command: >
-      sh -c "
-        echo 'Publishing Avro schemas to Nexus...' &&
-        ./gradlew publish --no-daemon &&
-        echo 'Avro schemas published successfully!' &&
-        exit 0
-      "
+#  avro-schemas:
+#    build:
+#      context: ../avro-schemas/
+#      dockerfile: Dockerfile
+#    environment:
+#      NEXUS_URL: ${NEXUS_AVRO_URL}
+#      NEXUS_USERNAME: ${NEXUS_USERNAME}
+#      NEXUS_PASSWORD: ${NEXUS_PASSWORD}
+#    networks:
+#      - iot-platform-net
+#    depends_on:
+#      nexus:
+#        condition: service_healthy
+#    command: >
+#      sh -c "
+#        echo 'Publishing Avro schemas to Nexus...' &&
+#        ./gradlew publish --no-daemon &&
+#        echo 'Avro schemas published successfully!' &&
+#        exit 0
+#      "
 
-  device-collector-service:
-    build:
-      context: ../device-collector-service/
-      dockerfile: Dockerfile
-      args:
-        NEXUS_URL: ${NEXUS_URL}
-        NEXUS_USERNAME: ${NEXUS_USERNAME}
-        NEXUS_PASSWORD: ${NEXUS_PASSWORD}
-    container_name: device-collector-service
-    ports:
-      - "9098:9098"
-    environment:
-      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
-      SCHEMA_REGISTRY_URL: ${SCHEMA_REGISTRY_URL}
-      ALLOY_URL: ${ALLOY_URL}
-      NEXUS_URL: ${NEXUS_URL}
-      NEXUS_USERNAME: ${NEXUS_USERNAME}
-      NEXUS_PASSWORD: ${NEXUS_PASSWORD}
-      KAFKA_POLL_TIMEOUT: ${KAFKA_POLL_TIMEOUT}
-      KAFKA_BATCH_LISTENER_ENABLED: ${KAFKA_BATCH_LISTENER_ENABLED}
-      KAFKA_CONCURRENCY: ${KAFKA_CONCURRENCY}
-      SLOW_SQL_QUERY_INDICATOR_MS: ${SLOW_SQL_QUERY_INDICATOR_MS}
-      DEVICE_COLLECTOR_KAFKA_CONSUMER_GROUP_ID: ${DEVICE_COLLECTOR_KAFKA_CONSUMER_GROUP_ID}
-      HIGHLIGHT_SQL: ${HIGHLIGHT_SQL}
-      FORMAT_SQL: ${FORMAT_SQL}
-      SHOW_SQL: ${SHOW_SQL}
-      SHARD_MASTER_0_JDBC_URL: ${SHARD_MASTER_0_JDBC_URL}
-      SHARD_MASTER_1_JDBC_URL: ${SHARD_MASTER_0_JDBC_URL}
-      SHARD_REPLICA_0_JDBC_URL: ${SHARD_REPLICA_0_JDBC_URL}
-      SHARD_REPLICA_1_JDBC_URL: ${SHARD_REPLICA_0_JDBC_URL}
-      SHARD_DB_USERNAME: ${SHARD_DB_USERNAME}
-      SHARD_DB_PASSWORD: ${SHARD_DB_PASSWORD}
-    networks:
-      - iot-platform-net
-    depends_on:
-      kafka:
-        condition: service_healthy
-      schema-registry:
-        condition: service_healthy
-      nexus:
-        condition: service_healthy
-      avro-schemas:
-        condition: service_completed_successfully  # ← Важно!
-      device_db_0:
-        condition: service_healthy
-      device_db_1:
-        condition: service_healthy
-      device_db_2:
-        condition: service_healthy
-      device_db_3:
-        condition: service_healthy
-    healthcheck:
-      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:9098/actuator/health" ]
-      interval: 15s
-      timeout: 5s
-      retries: 5
-      start_period: 30s
+#  device-collector-service:
+#    build:
+#      context: ../device-collector-service/
+#      dockerfile: Dockerfile
+#      args:
+#        NEXUS_URL: ${NEXUS_URL}
+#        NEXUS_USERNAME: ${NEXUS_USERNAME}
+#        NEXUS_PASSWORD: ${NEXUS_PASSWORD}
+#    container_name: device-collector-service
+#    ports:
+#      - "9098:9098"
+#    environment:
+#      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
+#      SCHEMA_REGISTRY_URL: ${SCHEMA_REGISTRY_URL}
+#      ALLOY_URL: ${ALLOY_URL}
+#      NEXUS_URL: ${NEXUS_URL}
+#      NEXUS_USERNAME: ${NEXUS_USERNAME}
+#      NEXUS_PASSWORD: ${NEXUS_PASSWORD}
+#      KAFKA_POLL_TIMEOUT: ${KAFKA_POLL_TIMEOUT}
+#      KAFKA_BATCH_LISTENER_ENABLED: ${KAFKA_BATCH_LISTENER_ENABLED}
+#      KAFKA_CONCURRENCY: ${KAFKA_CONCURRENCY}
+#      SLOW_SQL_QUERY_INDICATOR_MS: ${SLOW_SQL_QUERY_INDICATOR_MS}
+#      DEVICE_COLLECTOR_KAFKA_CONSUMER_GROUP_ID: ${DEVICE_COLLECTOR_KAFKA_CONSUMER_GROUP_ID}
+#      HIGHLIGHT_SQL: ${HIGHLIGHT_SQL}
+#      FORMAT_SQL: ${FORMAT_SQL}
+#      SHOW_SQL: ${SHOW_SQL}
+#      SHARD_MASTER_0_JDBC_URL: ${SHARD_MASTER_0_JDBC_URL}
+#      SHARD_MASTER_1_JDBC_URL: ${SHARD_MASTER_0_JDBC_URL}
+#      SHARD_REPLICA_0_JDBC_URL: ${SHARD_REPLICA_0_JDBC_URL}
+#      SHARD_REPLICA_1_JDBC_URL: ${SHARD_REPLICA_0_JDBC_URL}
+#      SHARD_DB_USERNAME: ${SHARD_DB_USERNAME}
+#      SHARD_DB_PASSWORD: ${SHARD_DB_PASSWORD}
+#    networks:
+#      - iot-platform-net
+#    depends_on:
+#      kafka:
+#        condition: service_healthy
+#      schema-registry:
+#        condition: service_healthy
+#      nexus:
+#        condition: service_healthy
+#      avro-schemas:
+#        condition: service_completed_successfully  # ← Важно!
+#      device_db_0:
+#        condition: service_healthy
+#      device_db_1:
+#        condition: service_healthy
+#      device_db_2:
+#        condition: service_healthy
+#      device_db_3:
+#        condition: service_healthy
+#    healthcheck:
+#      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:9098/actuator/health" ]
+#      interval: 15s
+#      timeout: 5s
+#      retries: 5
+#      start_period: 30s
 
 volumes:
   minio_data:
